# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bettering Magazine
email: your-email@domain.com
description: >
  Description here
baseurl: "/magazine" # the subpath of your site, e.g. /blog
url: "https:/bkazi.github.io/magazine" # the base hostname & protocol for your site
twitter_username:
instagram_username:
facebook_username:

# Build settings
markdown: kramdown

sass:
    style: compressed

brand-color: "#c2a972"
